### ISSUE TITLE
curl_code.cpp:28:23: fatal error ?

### ISSUE THREAD

**Issue by repsorp** [Great-Hill-Corporation/ethslurp#53]
Get this error when trying to build with 'make' :
curl_code.cpp:28:23: fatal error: curl/curl.h: No such file or folder
compilation terminated.

Ubuntu 15.10
g++ 5.2.1
curl 7.43.0

**Comment by tjayrush** [comment]
Hey. Thanks for contact us.

If you go to the root folder of your server and try looking in /usr/include or /usr/lib and do 

	find . -name “*.h” | grep curl

It should find it. You then may have to adjust the makefile a bit.

I am very bad with makefiles, build tools, etc. so if you know anything about how to better deliver source code, compiled binary, etc. I would love to see you join our github and help us out.

I can write c++ code. I can compile it in a very simple way, but all the makefile  stuff is a bridge too far.

On my Mac I use Xcode which hides all this detail from me.  

I’m happy to help you 100%, but I’m not must help there, I’m afraid. Perhaps we can help each other.

Cheers.

=======================
Thomas Jay Rush
Great Hill Corporation
jrush@greathill.com
(610) 519-9413

**Comment by repsorp** [comment]
'fatal error: curl/curl.h: No such file or folder' resolved by installing curl.h library:
http://askubuntu.com/questions/78183/installing-curl-h-library

Sorry I couldn't help you more, too much warning then:

importcontext.cpp:105:30: warning: ignoring return value of ‘char* fgets(char*, int, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
  fgets(buff, 4096*8, m_input);
                              ^
g++  -Wall -O2 -DLINUX -c fielddata.cpp -o objs/fielddata.o
g++  -Wall -O2 -DLINUX -c fieldlist.cpp -o objs/fieldlist.o
g++  -Wall -O2 -DLINUX -c point.cpp -o objs/point.o
g++  -Wall -O2 -DLINUX -c rect.cpp -o objs/rect.o
g++  -Wall -O2 -DLINUX -c runtimeclass.cpp -o objs/runtimeclass.o
g++  -Wall -O2 -DLINUX -c sfarchive.cpp -o objs/sfarchive.o
g++  -Wall -O2 -DLINUX -c sfdate.cpp -o objs/sfdate.o
g++  -Wall -O2 -DLINUX -c sffile.cpp -o objs/sffile.o
g++  -Wall -O2 -DLINUX -c sfos.cpp -o objs/sfos.o
sfos.cpp: In static member function ‘static int SFos::copyFile_Special(const SFString&, const SFString&)’:
sfos.cpp:64:31: warning: ignoring return value of ‘int system(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
  system((const char *)command);
                               ^
sfos.cpp: In static member function ‘static int SFos::copyFile(const SFString&, const SFString&)’:
sfos.cpp:101:31: warning: ignoring return value of ‘int system(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
  system((const char *)command);
                               ^
sfos.cpp: In static member function ‘static SFString SFos::doCommand(const SFString&, const SFString&)’:
sfos.cpp:209:46: warning: ignoring return value of ‘int system(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
  system((const char *)(cmd + ">" + filename));
                                              ^
sfos.cpp: In function ‘SFString getCWD(const SFString&)’:
sfos.cpp:260:29: warning*: ignoring return value of ‘char* getcwd(char*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
  ::getcwd(buffer, _MAX_PATH);

**Comment by repsorp** [comment]
'fatal error: curl/curl.h: No such file or folder' resolved by installing curl.h library:
http://askubuntu.com/questions/78183/installing-curl-h-library

Sorry I couldn't help you more, too much warning then:

importcontext.cpp:105:30: warning: ignoring return value of ‘char* fgets(char, int, FILE)’, declared with attribute warn_unused_result [-Wunused-result]
fgets(buff, 40968, m_input);
^
g++ -Wall -O2 -DLINUX -c fielddata.cpp -o objs/fielddata.o
g++ -Wall -O2 -DLINUX -c fieldlist.cpp -o objs/fieldlist.o
g++ -Wall -O2 -DLINUX -c point.cpp -o objs/point.o
g++ -Wall -O2 -DLINUX -c rect.cpp -o objs/rect.o
g++ -Wall -O2 -DLINUX -c runtimeclass.cpp -o objs/runtimeclass.o
g++ -Wall -O2 -DLINUX -c sfarchive.cpp -o objs/sfarchive.o
g++ -Wall -O2 -DLINUX -c sfdate.cpp -o objs/sfdate.o
g++ -Wall -O2 -DLINUX -c sffile.cpp -o objs/sffile.o
g++ -Wall -O2 -DLINUX -c sfos.cpp -o objs/sfos.o
sfos.cpp: In static member function ‘static int SFos::copyFile_Special(const SFString&, const SFString&)’:
sfos.cpp:64:31: warning: ignoring return value of ‘int system(const char)’, declared with attribute warn_unused_result [-Wunused-result]
system((const char )command);
^
sfos.cpp: In static member function ‘static int SFos::copyFile(const SFString&, const SFString&)’:
sfos.cpp:101:31: warning: ignoring return value of ‘int system(const char)’, declared with attribute warn_unused_result [-Wunused-result]
system((const char )command);
^
sfos.cpp: In static member function ‘static SFString SFos::doCommand(const SFString&, const SFString&)’:
sfos.cpp:209:46: warning: ignoring return value of ‘int system(const char)’, declared with attribute warn_unused_result [-Wunused-result]
system((const char )(cmd + ">" + filename));
^
sfos.cpp: In function ‘SFString getCWD(const SFString&)’:
sfos.cpp:260:29: warning: ignoring return value of ‘char* getcwd(char*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
::getcwd(buffer, _MAX_PATH);

**Comment by tjayrush** [comment]
Thanks for your help. Do you know what I think I’ll do? I think I’ll try to get it compile myself on Ubuntu and repost the fixes. 

Thanks. I’m sure these are just simple things to fix. Thanks for your feedback.

I just have to find an ubuntu box. I had one at digital ocean a while ago, but I haven’t tried compiling this there yet.


=======================
Thomas Jay Rush
Great Hill Corporation
jrush@greathill.com
(610) 519-9413

**Comment by repsorp** [comment]
That would be nice
Keep up the good work

Le 11. 06. 16 19:38, Thomas Jay Rush a écrit :
> Thanks for your help. Do you know what I think I’ll do? I think I’ll try
> to get it compile myself on Ubuntu and repost the fixes.
> 
> Thanks. I’m sure these are just simple things to fix. Thanks for your
> feedback.
> 
> I just have to find an ubuntu box. I had one at digital ocean a while
> ago, but I haven’t tried compiling this there yet.
> 
> 
> =======================
> Thomas Jay Rush
> Great Hill Corporation
> jrush@greathill.com
> (610) 519-9413
> 
>> On Jun 11, 2016, at 1:36 PM, repsorp <notifications@github.com> wrote:
>>
>> 'fatal error: curl/curl.h: No such file or folder' resolved by
> installing curl.h library:
>> http://askubuntu.com/questions/78183/installing-curl-h-library
>>
>> Sorry I couldn't help you more, too much warning then:
>>
>> importcontext.cpp:105:30: warning: ignoring return value of ‘char*
> fgets(char, int, FILE)’, declared with attribute warn_unused_result
> [-Wunused-result]
>> fgets(buff, 40968, m_input);
>> ^
>> g++ -Wall -O2 -DLINUX -c fielddata.cpp -o objs/fielddata.o
>> g++ -Wall -O2 -DLINUX -c fieldlist.cpp -o objs/fieldlist.o
>> g++ -Wall -O2 -DLINUX -c point.cpp -o objs/point.o
>> g++ -Wall -O2 -DLINUX -c rect.cpp -o objs/rect.o
>> g++ -Wall -O2 -DLINUX -c runtimeclass.cpp -o objs/runtimeclass.o
>> g++ -Wall -O2 -DLINUX -c sfarchive.cpp -o objs/sfarchive.o
>> g++ -Wall -O2 -DLINUX -c sfdate.cpp -o objs/sfdate.o
>> g++ -Wall -O2 -DLINUX -c sffile.cpp -o objs/sffile.o
>> g++ -Wall -O2 -DLINUX -c sfos.cpp -o objs/sfos.o
>> sfos.cpp: In static member function ‘static int
> SFos::copyFile_Special(const SFString&, const SFString&)’:
>> sfos.cpp:64:31: warning: ignoring return value of ‘int system(const
> char)’, declared with attribute warn_unused_result [-Wunused-result]
>> system((const char )command);
>> ^
>> sfos.cpp: In static member function ‘static int SFos::copyFile(const
> SFString&, const SFString&)’:
>> sfos.cpp:101:31: warning: ignoring return value of ‘int system(const
> char)’, declared with attribute warn_unused_result [-Wunused-result]
>> system((const char )command);
>> ^
>> sfos.cpp: In static member function ‘static SFString
> SFos::doCommand(const SFString&, const SFString&)’:
>> sfos.cpp:209:46: warning: ignoring return value of ‘int system(const
> char)’, declared with attribute warn_unused_result [-Wunused-result]
>> system((const char )(cmd + ">" + filename));
>> ^
>> sfos.cpp: In function ‘SFString getCWD(const SFString&)’:
>> sfos.cpp:260:29: warning: ignoring return value of ‘char*
> getcwd(char*, size_t)’, declared with attribute warn_unused_result
> [-Wunused-result]
>> ::getcwd(buffer, _MAX_PATH);
>>
>> —
>> You are receiving this because you commented.
>> Reply to this email directly, view it on GitHub, or mute the thread.
>>
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/Great-Hill-Corporation/ethslurp/issues/53#issuecomment-225379316>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGAVyM1E5S92IY9W-RINVpqWo-BLpXF4ks5qKvKtgaJpZM4IzloW>.
> 

-- 
GnuPG Key ID: 0x59491815

**Comment by tjayrush** [comment]
Curl code has been re-written to make it simpler. Also, INSTALL.md file now has instructions for building on ubuntu.
