### ISSUE TITLE
Finish doing the 'build from source' for ubuntu

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/ethslurp#57]
And windows

**Comment by rolandkofler** [comment]
yeah can't compile it on Ubuntu...
`make[1]: Leaving directory `/home/roland/programs/Great-Hill-Corporation-ethslurp-83244a6/etherlib'
ethslurp build started
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
make[1]: Entering directory `/home/roland/programs/Great-Hill-Corporation-ethslurp-83244a6'
g++  -Wall -O2 -DLINUX -I. -I./utillib -I./etherlib -c ethslurp.cpp -o objs/ethslurp.o
g++  -Wall -O2 -DLINUX -I. -I./utillib -I./etherlib -c options.cpp -o objs/options.o
options.cpp: In member function ‘SFInt32 COptions::parseArguments(SFInt32, const SFString*)’:
options.cpp:180:42: warning: ignoring return value of ‘int system(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
     system("open ~/.ethslurp/config.dat");
                                          ^
make[1]: *** No rule to make target `utillib/utillib.a', needed by `ethslurp'.  Stop.
make[1]: Leaving directory `/home/roland/programs/Great-Hill-Corporation-ethslurp-83244a6'
make: *** [all] Error 2
`

**Comment by tjayrush** [comment]
All compile bugs and warnings should be fixed on ubuntu now. See the INSTALL.md file in main folder.
