### ISSUE TITLE
Is it possible to pull a list of transactions in morden

### ISSUE THREAD

**Issue by cheershendtco** [Great-Hill-Corporation/ethslurp#90]
hihi
Is it possible to pull a list of transactions in morden
Thanks!

**Comment by tjayrush** [comment]
At this line (https://github.com/Great-Hill-Corporation/ethslurp/blob/master/ethslurp.cpp#L226) ethslurp builds a URL that accesses the http://etherscan.io APIs. I do not know if etherscan.io provides an API to the morden testnet. If it does, you should be able to adjust that URL. If not, then you may be able to find another API that does, but I don't know of any. If you do use a different API, you may have to adjust field names, etc.  I'd be interested in hearing the results of your inquiry.

**Comment by wighawag** [comment]
I tested and you can use https://testnet.etherscan.io/api?...

**Comment by tjayrush** [comment]
That's excellent. I'll add this information to the README file and close this issue. Thanks.

**Comment by sebs** [comment]
There is [etherscan-api](https://github.com/sebs/etherscan-api) on npm
