### ISSUE TITLE
Output function's arguments as json

### ISSUE THREAD

**Issue by wighawag** [Great-Hill-Corporation/ethslurp#97]
Would be great to have function arguments  decoded via the abi information and be shown as json object in the output:

for example for function "transfer" it would be
```
"decoded_inputs" : {"_to":"0xfdfdf...", "_amount":"10000"}
```

**Comment by tjayrush** [comment]
Great idea. I'll get back to you tomorrow.

**Comment by tjayrush** [comment]
Two things:

1) Can you do me a favor? Can you send me a single .json object representing one function call where you've taken the current output and physically inserted the "decoded_input"? In this way, I will be sure to give you the output you want without us having to go back and forth.

2) This will require a change in the binary format of the saved 'slurp.' Currently, there is no way to 'clear the cache,' so before running the next version (with the decoded_inputs field) you will have to manually 'clear the cache' yourself. You do this by removing all the *.bin files in ~/.ethslurp/slurps.

**Comment by wighawag** [comment]
for 
```
 //function start(string gameID, uint64 blockNumber,uint8 competitionIndex, uint32 version)
```
it would be something like :
```
{
...
"decoded_input":{
 "gameID" : "catchme",
 "blockNumber" : "123000",
 "competitionIndex" : 1,
 "version" : 63
},
...
}
```

for this 
```
//function submit(string gameID, uint64 seed, uint32 score, uint32 durationRoundedDown, bytes32 proofHash)
```

it would be something like :
```
{
...
"decoded_input":{
 "gameID" : "catchme",
 "seed" : "12390415930956723389",
 "score" : 12000,
 "durationRoundedDown" : 163,
 "proofHash" :"0x8b638e78c8d9160620db7c539ae2cb24b614e2ad89136437c2c0b808d9724338"
},
...
}
```

**Comment by wighawag** [comment]
In the above comment I forgot to include the function name so I came up with the following format

```
{
...
"decoded_call": 
   { 
     "name": "start",
     "input": 
      { 
         "gameID": "catchme",
        "blockNumber": "122"  
        "competitionIndex": 1,
        "version": 2
     }
  }
...
}
```

**Comment by tjayrush** [comment]
Moved to https://github.com/Great-Hill-Corporation/quickBlocks/issues/71
